### ISSUE TITLE
搭建SSR服务器出错

### ISSUE THREAD

**Issue by CyshallChan** [shadowsocksr/shadowsocksr#192]
跟着教程到python server.py这一步出现下面的错误，还请dalao能帮忙看下什么原因：

loaded collections.OrderedDict
IPv6 support
Traceback (most recent call last):
  File "server.py", line 215, in <module>
    main()
  File "server.py", line 38, in main
    config = shell.get_config(False)
  File "/root/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 304, in get_config
    check_config(config, is_local)
  File "/root/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 135, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/root/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/root/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/root/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/root/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 71, in __init__
    load_libsodium()
  File "/root/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found

**Comment by breakwa11** [comment]
@CyshallChan 没安装libsodium

**Comment by CyshallChan** [comment]
@breakwa11  额，我后面换了别的加密方式就没报这个错误。但是又新出现另外一个问题：
[root@li753-222 shadowsocks]# python server.py 
loaded collections.OrderedDict
IPv6 support
2017-03-06 14:55:53 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2017-03-06 14:55:53 INFO     shell.py:72 ShadowsocksR 3.0.2 2017-01-08
2017-03-06 14:55:53 INFO     server.py:46 current process RLIMIT_NOFILE resource: soft 1024 hard 4096
2017-03-06 14:55:53 INFO     asyncdns.py:324 dns server: [('106.187.90.5', 53), ('106.187.93.5', 53), ('106.187.94.5', 53)]
2017-03-06 14:55:53 INFO     server.py:106 server start with protocol[auth_aes128_md5] password [qq825721417] method [aes-128-cfb] obfs [http_simple] obfs_param []
2017-03-06 14:55:53 INFO     server.py:122 starting server at [::]:8388
2017-03-06 14:55:53 INFO     server.py:142 starting server at 106.187.96.148:8388
这样应该说明服务启动成功了阿。
-----------------------------------------------------------------------------------------------------------------
tcp        0      0 :::8388                     :::*                        LISTEN      7915/python    
然后我又看了下端口，SSR的端口8388也在监听了，然后PC客户端服务器，端口，加密方式等等设置都和服务端一样，但仍然翻不了墙，这到底是怎么回事阿。（服务器可以访问google）

**Comment by breakwa11** [comment]
@CyshallChan 防火墙

**Comment by CyshallChan** [comment]
@breakwa11
iptables: Setting chains to policy ACCEPT: security raw nat[FAILED]filter 
iptables: Flushing firewall rules:                         [  OK  ]
iptables: Unloading modules:                            [  OK  ]

防火墙关了也不行。。

**Comment by breakwa11** [comment]
server字段复原为0.0.0.0，然后自己用tcping测试，如果还是连接失败，自己换服务器IP再测

**Comment by Hanjiangke** [comment]
我也是连接不上的问题
![image](https://cloud.githubusercontent.com/assets/7166138/23660974/2589e2b0-0386-11e7-83b0-ebc2c4016d3f.png)

**Comment by Z4HD** [comment]
截图不打码，这样暴露IP真的好吗？
