### ISSUE TITLE
服务端无法读取数据库中排序靠后用户的信息

### ISSUE THREAD

**Issue by cccatcc** [shadowsocksr/shadowsocksr#220]
近日不少新注册的用户反映无法使用，测试排查之后发现，出现问题的用户的UID都大于8400，  服务端具体表现为读取用户信息至一定数量后出现如下报错：
```
2017-04-17 02:56:59 INFO     db_transfer.py:199 db start server at port [45192] pass [*******] protocol [auth_sha1_v4_compatible] method [chacha20] obfs [http_simple_compatible]
2017-04-17 02:56:59 INFO     server_pool.py:128 starting server at [::]:45192
2017-04-17 02:56:59 INFO     server_pool.py:154 starting server at 0.0.0.0:45192
2017-04-17 02:56:59 ERROR    db_transfer.py:260 Traceback (most recent call last):
  File "/root/ssr-mu/db_transfer.py", line 256, in thread_db
    db_instance.del_server_out_of_bound_safe(last_rows, rows)
  File "/root/ssr-mu/db_transfer.py", line 113, in del_server_out_of_bound_safe
    cfg[name] = cfg[name].encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1: ordinal not in range(128)
```
尝试更新了目前最新版本（Apr 14, 2017）的服务端依然存在该问题，不过换成2016-12-23版本的服务端则没有该问题。

**Comment by cccatcc** [comment]
经@breakwa11 指导排查，实为一用户设置的连接密码包含空格，导致后面的用户都无法连接，将这个用户的连接密码中的空格删除后，问题解决。
