### ISSUE TITLE
git pull之后,ssr不能启动了

### ISSUE THREAD

**Issue by CarnivalO** [shadowsocksr/shadowsocksr#238]
通过python server.py启动正常使用
通过logrun.sh,run.sh启动就不能使用
下面是logrun记录.
这个是代码问题嘛?
```
2017-05-25 16:25:56 ERROR    db_transfer.py:264 Traceback (most recent call last):
  File "/root/shadowsocksr/db_transfer.py", line 246, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/db_transfer.py", line 371, in pull_db_all_user
    import cymysql
ImportError: No module named 'cymysql'

root@vultr:~/shadowsocksr# pip install cymysql
Requirement already satisfied: cymysql in /usr/local/lib/python2.7/dist-packages
root@vultr:~/shadowsocksr# git pull
Already up-to-date.
root@vultr:~/shadowsocksr#
```

**Comment by breakwa11** [comment]
@CarnivalO 用内置脚本安装cymysql，看wiki

**Comment by U201513887** [comment]
git pull后有类似问题不过是 ImportError: No module named 'json'
但是已经安装python2.7，用脚本单独地import json正常
通过python server.py启动正常使用
用的是mudbjson版

Traceback (most recent call last):
  File "server.py", line 27, in <module>
    import server_pool
  File "/root/shadowsocksr/server_pool.py", line 28, in <module>
    from shadowsocks import shell, eventloop, tcprelay, udprelay, asyncdns, common
  File "/root/shadowsocksr/shadowsocks/shell.py", line 22, in <module>
    import json
ImportError: No module named 'json'

**Comment by U201513887** [comment]
貌似把logrun.sh和run.sh里 ${python_ver} 改成python 后可正常运行
