### ISSUE TITLE
运行后不正常自动停止运行

### ISSUE THREAD

**Issue by tinchbear** [shadowsocksr/shadowsocksr#244]
服务器版本：ShadowsocksR 3.3.3.1 2017-06-03 mod by esdeathlove
服务器系统：Fedora 25 Kernel 4.11.3
Python版本：3.5.3

运行一段时间后，会出现以下错误，之后将自动停止运行：
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    common.py:415 unable to parse hostname exodus.desync.com when resolve DNS
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    common.py:415 unable to parse hostname torrent.gresille.org when resolve DNS
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    common.py:415 unable to parse hostname tracker.aletorrenty.pl when resolve DNS
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    common.py:415 unable to parse hostname tracker.baravik.org when resolve DNS
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    shell.py:50 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
2017-06-03 14:50:58 ERROR    server_pool.py:100 _handle_server_dns_resolved() takes exactly 10 arguments (9 given)
Traceback (most recent call last):
  File "/usr/local/shadowsocks/server_pool.py", line 93, in _loop
    loop.run()
  File "/usr/local/shadowsocks/shadowsocks/eventloop.py", line 222, in run
    handle = handler.handle_event(sock, fd, event) or handle
  File "/usr/local/shadowsocks/shadowsocks/asyncdns.py", line 429, in handle_event
    self._handle_data(data)
  File "/usr/local/shadowsocks/shadowsocks/asyncdns.py", line 405, in _handle_data
    self._call_callback(hostname, ip)
  File "/usr/local/shadowsocks/shadowsocks/asyncdns.py", line 364, in _call_callback
    callback((hostname, ip), error)
  File "/usr/local/shadowsocks/shadowsocks/common.py", line 421, in _handle_dns_resolved
    self.call_back(self.remote_addr, None, ip, True, *self.params)
TypeError: _handle_server_dns_resolved() takes exactly 10 arguments (9 given)

**Comment by breakwa11** [comment]
更新
