### ISSUE TITLE
cymysql已经安装但是运行的时候却用不了

### ISSUE THREAD

**Issue by Csedge** [shadowsocksr/shadowsocksr#263]
[cloudsigma@CentOS-6-9 shadowsocksrv2]$ pip install cymysql
Requirement already satisfied: cymysql in /usr/local/lib/python2.7/site-packages
[cloudsigma@CentOS-6-9 shadowsocksrv2]$ puthon server.py
-bash: puthon: command not found
[cloudsigma@CentOS-6-9 shadowsocksrv2]$ sudo python server.py
loaded collections.OrderedDict
IPv6 support
2017-06-24 07:20:29 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2017-06-24 07:20:29 INFO     asyncdns.py:324 dns server: [('116.93.119.119', 53), ('162.213.38.38', 53), ('178.22.66.167', 53)]
2017-06-24 07:20:29 INFO     shell.py:72 ShadowsocksR 3.1.0 2017-03-16
2017-06-24 07:20:29 INFO     db_transfer.py:232 current process RLIMIT_NOFILE resource: soft 1024 hard 4096
2017-06-24 07:20:29 ERROR    db_transfer.py:260 Traceback (most recent call last):
  File "/home/cloudsigma/shadowsocksrv2/db_transfer.py", line 242, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/home/cloudsigma/shadowsocksrv2/db_transfer.py", line 367, in pull_db_all_user
    import cymysql
ImportError: No module named cymysql

^[OQ^Z
[6]+  Stopped                 sudo python server.py

**Comment by breakwa11** [comment]
@Csedge 安装方法错误，请用WIKI里的方法

**Comment by Csedge** [comment]
好
