### ISSUE TITLE
linux 安装未找到sql

### ISSUE THREAD

**Issue by sunchenxin98** [shadowsocksr/shadowsocksr#265]
![image](https://user-images.githubusercontent.com/26816025/27757969-7fe16074-5e3c-11e7-87c5-7af01b160bff.png)
db_transfer.py:264 Traceback (most recent call last):
  File "/root/shadowsocksr/db_transfer.py", line 246, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/db_transfer.py", line 384, in pull_db_all_user
    rows = self.pull_db_users(conn)
  File "/root/shadowsocksr/db_transfer.py", line 400, in pull_db_users
    cur.execute("SELECT " + ','.join(keys) + " FROM user")
  File "/root/shadowsocksr/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/root/shadowsocksr/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/root/shadowsocksr/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
ProgrammingError: (1146, u"Table 'sspanel.user' doesn't exist")

^CTraceback (most recent call last):
  File "server.py", line 58, in main
    thread.join(10.0)
  File "/usr/lib64/python2.7/threading.py", line 961, in join
    self.__block.wait(delay, balancing)
  File "/usr/lib64/python2.7/threading.py", line 361, in wait
    _sleep(delay)
KeyboardInterrupt

**Comment by breakwa11** [comment]
错误不是说得很清楚吗，到底怎么了

**Comment by sunchenxin98** [comment]
原因是，我今早没有看到找到 sql文件所以，上面的 问题就是想问sql 在哪。现在已经找到了。 可能表达不是很清楚抱歉。

**Comment by wwyy456258** [comment]
建表语句真的好难找啊

**Comment by sunchenxin98** [comment]
https://github.com/orvice/ss-panel/blob/master/db-testing.sql
