### ISSUE TITLE
Exception: cipher aes-128-ctr not found in libcrypto

### ISSUE THREAD

**Issue by depfish** [shadowsocksr/shadowsocksr#271]
在mac上执行: python local.py -c config.json 
会报如下错误

python local.py -c config.json 
loaded collections.OrderedDict
IPv6 not support
2017-07-11 18:21:46 INFO     util.py:85 loading libcrypto from /usr/lib/libcrypto.dylib
Traceback (most recent call last):
  File "local.py", line 81, in <module>
    main()
  File "local.py", line 43, in main
    config = shell.get_config(True)
  File "/Users/ggmm/Documents/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 299, in get_config
    check_config(config, is_local)
  File "/Users/ggmm/Documents/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/Users/ggmm/Documents/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/Users/ggmm/Documents/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/Users/ggmm/Documents/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/Users/ggmm/Documents/shadowsocksr/shadowsocks/../shadowsocks/crypto/openssl.py", line 94, in __init__
    raise Exception('cipher %s not found in libcrypto' % cipher_name)
**Exception: cipher aes-128-ctr not found in libcrypto**

**Comment by breakwa11** [comment]
@depfish 更新你自己的libcrypto，错误信息已经说得很清楚
